// <auto-generated />
namespace UniversityofLouisvilleVaccine.DataContexts.GrantsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_return));
        
        string IMigrationMetadata.Id
        {
            get { return "201504070713097_return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
